### PR TITLE
Outdated test files [Test]

### PR DESCRIPTION
**Pull request by anithri**
there (tentatively) are 30 more of these.  Do you want me to PR away?  One at a time, by class or all in one go?

### CODE REVIEW

**Comment by trans** [comment]
Even though it's probably a pain, the fewer at once the better, just so it's easier for me to review them.

So these are lingering tests from methods that were removed because they are now part of Ruby proper. I can understand why I overlooked them in that the tests themselves would still pass regardless. But what has me scratching my head is why the `covers 'facets/enumerable/one'` line doesn't raise an error, since there is no longer such a file to require? (`covers` calls `require`, btw) Will have to look into that at some point.

P.S. Very much appreciate your use of commit tags! (No one else ever caught on to that.)  One change though, I recently switched to, e.g., `:test:` notation instead of `[test]`. Did this so they (or at least some) will appear as emojis on github. It seems to be a trend that is catching on. Also, I haven't decided if they should be at the front or back of the first line of the message. So at this point either way is fine. Do whichever seems best to you.

**Comment by anithri** [comment]
I tried to follow the contribution guidelines, but I can switch to the other style.  Will that be true for tags like :minor: too?

 I'm not sure why your tests are passing, but I know I had to comment out a bunch of tests (~30) in order to get the one I added for string/random to even run.

I'll start busting out those removal PR's a couple at a time.

**Comment by trans** [comment]
Yes, all of them, `:minor:` too. I need to update the guidelines. I'll do that today. 

Well I am glad the tests failed for you at least. I can understand on my system it might have simply been b/c it was picking up the old methods from an old version of Facets. But what concerns me is that they passed on Travis CI too, which is what I was depending on as the definitive results. That shouldn't have happened, and I need to look into it. So Big Thanks for letting me know.

And thanks for all your work. I haven't had the much time to devote to it in the last year, so your contributions are making a big difference.

**Comment by anithri** [comment]
Glad to help out, just let me know when you are sick of PRs :smile:

**Pull request merged**
