### PR TITLE
Implementation and test of Enumerable#with_position

### PR DESCRIPTION
**Pull request by ioquatix**

### CODE REVIEW

**Comment by ioquatix** [comment]
Once this is merged, can you please release 3.2? Thanks. Also, I'm still interested in assisting with the management of this project. It requires a lot of work but I'd be happy to start modernising some of the code.

**Comment by trans** [comment]
I appreciate the elegance of this API, but performance wise I suspect this is not going to be worth the trade-off.

```ruby
a.each_with_index do |v, i|
  i == 0  # first
  i > 0    # middle
  i == a.size - 1  # last
end
```

Not as pretty, but there is almost no overhead involved.

Also, I tried to benchmark this to see the exact difference, and got an error running:

```ruby
a = (1..100000000).to_a
a.with_position do |v, pos|
  pos.first?
  pos.middle?
  pos.last
end
```

Looking at the code, I think you need to use the `#next` and `#peek` on the enumerator not `self`. But when I tried that, I got the error: `in `next': mprotect failed (FiberError)`. Off hand I am not sure what the problem is there.

**Comment by trans** [comment]
Thinking about it a bit more I think a way to do it simply to have class that references the enumerable object and the index.

```ruby
    def with_position
      each_with_index do |v,i|
        yield v, Position.new(self, i)
      end
    end
```

Then simply define the methods on `Position` in terms of I and the enumerable object. e.g.

```
  def first?
    @i == 0
  end

  def last?
    @i == @self.size - 1
  end
```

**Comment by ioquatix** [comment]
It might already exist.

You are right it's not high performance and there are alternatives.

But you are also missing the main use case: when chaining with other functional operators where index is meaningless.

**Comment by ioquatix** [comment]
```ruby
a.each_with_index do |v, i|
  i == 0           # first
  i > 0            # middle
  i == a.size - 1  # last
end
```

You are assuming a is accessible but it's not when you chain things together, e.g. `object.complex_computation.each.with_position` or `array.select{...}.each.with_position`.

**Pull request merged**
