### PR TITLE
Added Object#or

### PR DESCRIPTION
**Pull request by codeindulgence**

### CODE REVIEW

**Comment by trans** [comment]
Interesting. At first I thought there must already be some method that does this, but after a quick search, I found none. So I'm inclined to accept this. The name might be confused for a method based logical-or, but I'm not to concerned about it. Really my only reservation is that it is `nil` only, and doesn't work for `false`. Is there a good reason for this?

**Comment by codeindulgence** [comment]
Nope, I hadn't actually thought about that.
It's basically short hand for ternary `some_var ? some_var : other_var`.
That's right short hand for a short hand syntax! I just don't like the look of repeating `some_var`.

I just did a quick IRB sense check and the following seems to work:
```
class Object
  def or(obj)
    self ? self : obj
  end
end
```

What do you think?

**Comment by kotp** [comment]
`self or obj` is much more succinct than the ternary.

**Comment by trans** [comment]
@kotp makes a good point. Unless there is a good reason to treat `false` and `nil` differently (and I'm not sure there is) then your `object.or(other)` is the same as `object or other` or `object || other`. Do we need a method form of this? It does nothing new and will be slower.

**Comment by codeindulgence** [comment]
Hah, yeh. Can't believe I missed that.
Withdrawn!

**Comment by trans** [comment]
No problem. I didn't catch it at first either. Thanks for contributing just the same.

**Pull request closed without merging**
