### PR TITLE
Add demo and remove test for array contains

### PR DESCRIPTION
**Pull request by anithri**

### CODE REVIEW

**Comment by trans** [comment]
Is `Array#contains?` being called/tested any where in the unit tests now? It still needs to be in there somewhere even if it is just a single call (b/c we know it is an alias)...

Actually I think I am having second thoughts about this approach. I think it should be the other way around. The unit tests are intended to be very thorough, while the demos are focused more on documentation. So lets have the duplication in the tests, and then in the demos, just mention that `#contains?` is an alias of `#include?` and give one example (what you have in that respect if fine).

The redundancy might be a pain, and really it doesn't have to be 100% duplication. But should the alias ever change, say it is decide the `#contains` should have a slightly different meaning, then those tests will prove very helpful.

**Comment by anithri** [comment]
I was looking at the demos as an acceptance test with bonus documentation, demonstrating that the alias works in a unit test smacks of testing the language.  My thought was to build the demos up to the point where they demonstrate everything and serve as a discovery mechanism and documentation for methods.  And use the tests to make sure the implementation does what we think it does.

So we add back the test file, do a simple test to prove the alias is working and to help guard against future changes or potential duplications of the method name?

**Comment by trans** [comment]
> I was looking at the demos as an acceptance test with bonus documentation

I see. It's more the other way around in the case of Facets. 

> demonstrating that the alias works in a unit test smacks of testing the language. 

That's true, it does. But should the alias ever change, or become broken then it will be worth having.

> My thought was to build the demos up to the point where they demonstrate everything and serve as a discovery mechanism and documentation for methods. And use the tests to make sure the implementation does what we think it does.

That's exactly right. They should demonstrate everything, but they won't be exhaustive. The tests will have cases that are beyond the scope of the demos, e.g. esoteric edge cases will be in the tests, but they won't be in the demos b/c they aren't important for common usage.

**Comment by anithri** [comment]
OK, I'm closing this PR then (and not just because I merged upstream into it on accident)

**Pull request closed without merging**
