### PR TITLE
Add tests enumerable hashify

### PR DESCRIPTION
**Pull request by anithri**
I think the changes should be clear between the commit message and code changes

### CODE REVIEW

**Comment by anithri** [comment]
Is there a way to run a test for a single file at a time? The test-runner and rake tasks run every test when every time no matter what arguments or ENV i set.  And the long test run is driving me nuts.  It not that long, but's it's long enough that I have to wait for some slow tests every time.

**Comment by anithri** [comment]
I did some tests for splat about using other methods to solve the odd element problem.  The ways to do this without size are limited. 

1. use Enumerable.count and skip the dup, which is a tiny bit slower than the current method
2. use something like each_slice(2) to split the enumerable into pairs, pad the last element, and stuff it into an hash.  But this is MUCH slower than the current method
3. catch the ArgumentError that Hash[] throws on and odd size.  But Benchmarked it's a tiny bit slower than the current method.

The only improvement I can think of is implemented below.  Changing this is necessary to allow enumerables like Range to avoid raising an error by calling << on Range.  It also prevents having to traverse the enumerable more than once.

**Comment by trans** [comment]
There may be no good way around the use of `size`. The problem with using it, of course, is that some enumerables don't support it, and some do but have to traverse themselves to get a count, which is slow. Your last option makes me think that perhaps we shouldn't handle the odd size case at all and an error should just be raised.

**Comment by trans** [comment]
Comment out these lines in `etc/test.rb`.

```ruby
Test.run do |r|
  r.files << 'test'
end
```

Now you should be able to run individual tests by passing the test file(s) to the rubytest command.

**Pull request merged**
